# Generated by Django 3.2.9 on 2021-11-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
