# Generated by Django 3.2.9 on 2021-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('C', 'Concluído')], max_length=1, null=True),
        ),
    ]
